### ISSUE TITLE
Long puppet run with 7-7-stable 

### ISSUE THREAD

**Issue by patricklindeman** [Aethylred/puppet-gitlab#3]
Hi, 
First of all great work, your gitlab module installs and runs great, thanks for that!
 
Just one minor "issue". I'm using the example from init-7.7.pp to install the 7-7-stable version of gitlab which works like a charm. But now every puppet run on this host takes about 12 minutes and during the puppet-run it takes 100% cpu for a single core. It looks like a complete git-checkout is done over and over again. Am I missing something or is this "normal" behaviour?

**Comment by Aethylred** [comment]
This is 'normal' there's an outstanding issue with Puppet doing exactly this when checking permissions on lots of files (which this module does): https://tickets.puppetlabs.com/browse/PUP-3043

However, having a PuppetDB setup and running on PostgreSQL helps substantially, more so if the PuppetDB server is separate from the Puppetmaster. It would seem that this problem is mostly external to the module. I'd recommend changing the `runinterval` on the gitlab host to a high number like `7200` (every two hours) or longer.

However I am looking at tuning the module further, but I'm working on my puppetmaster, puppetdb, and node performance tuning first.

**Comment by patricklindeman** [comment]
Ok fair enough, unfortunately its not that easy to schedule host-based runintervals. So for now we've decided to go a different way and not use the puppet git checkout/install of gitlab.

**Comment by Aethylred** [comment]
I've excluded a couple of directories from the recursion and that's made a large difference. It now runs in about 1/10th the time.
